### ISSUE TITLE
Conversion to SRT adds extra carriage return (CR) character to each line [v0.1.9, win64]

### ISSUE THREAD

**Issue by kanoary** [QNapi/qnapi#33] opened 2015-11-15 19:20 UTC
When file is converted to SRT, an extra CR character is added to every line, so you end up with sequence of: CR, CR, LF. In notepad you can see an empty line every second line. This makes SRT files unreadable on TV such as SONY bravia.

**Comment by krzemin** [comment] 2015-11-15 19:37
Duplicate of #29

**Closed by krzemin** 2015-11-15 19:37 UTC
Labels: duplicate
