### ISSUE TITLE
Subtitle downloading problem (Linux, 0.2.0, x64) 

### ISSUE THREAD

**Issue by miniworm** [QNapi/qnapi#41] opened 2015-11-26 19:26 UTC
Subtitles are not downloaded when i switch on file conversion. With this set to off downloading works ok. When it's enabled i get dialogs about selecting one of many available subtitles but finally no subtitle file is created in directory.

**Comment by krzemin** [comment] 2015-11-27 09:37
Please provide more information.
1. Link to a movie file (or torrent) you are downloading subtitles for.
2. QNapi configuration file (`qnapi.ini`)

**Comment by miniworm** [comment] 2015-11-27 16:51
I've provided few more details in #37 . Sorry, no links to torrents or files since i've tried with files on my HDD, which I've from my friend. But i've tried with few files and it works the same way with all of them.

Here is my qnapi.ini file:

[qnapi]
7z_path=/usr/bin/7z
auto_detect_encoding=false
change_permissions=false
download_policy=1
enc_from=windows-1250
enc_to=windows-1250
encoding_method=0
engines=@Variant(\0\0\0\v\0\0\0\x2\0\0\0\x16\0N\0\x61\0p\0i\0P\0r\0o\0j\0\x65\0k\0t\0\0\0\x2\0\x31), @Variant(\0\0\0\v\0\0\0\x2\0\0\0\x1a\0O\0p\0\x65\0n\0S\0u\0\x62\0t\0i\0t\0l\0\x65\0s\0\0\0\x2\0\x31), @Variant(\0\0\0\v\0\0\0\x2\0\0\0\x10\0N\0\x61\0p\0i\0s\0y\0\x32\0\x34\0\0\0\x2\0\x31)
ffprobe_path=/usr/bin/ffprobe
firstrun=false
language=pl
language_backup=en
nick=
no_backup=false
pass=
permissions=644
post_processing=true
prev_dialog_path=/media/Video/
quiet_batch=false
remove_lines=false
remove_words=movie info, "synchro "
search_policy=0
show_all_encodings=false
skip_convert_ads=true
sub_ext=
sub_format=
tmp_path=/tmp
use_brushed_metal=true
version=0.2.1

**Comment by miniworm** [comment] 2015-11-27 16:52
Also simple file conversion from menu doesn't work - when i select TXT file and want it to be converted to SRT. FTS checking works but then no conversion takes place.

**Comment by krzemin** [comment] 2015-11-27 17:33
I can confirm that after subtitle selection dialog, only when you select subtitles provided by **OpenSubtitles** engine, they are not downloaded. But it doesn't matter whether format/encoding conversion is enabled. When I selected subtitles provided by NapiProjekt or Napisy24, everything worked as expected.
The most probably it is a problem with OpenSubtitles API. Try disabling OpenSubtitles engine and check whether you can reproduce the problem.

Regarding problems with file conversion from menu, please don't mix different topics in a single issue. If there is a problem - create another issue and describe all the details like source/destination formats and providing original source file.

**Comment by miniworm** [comment] 2015-11-29 11:24
Sadly it doesn't change for better after disabling OpenSubtitles. Files are downloaded when i set original format but not after enabling format conversion (tried with both NapiProjekt and Napisy24).

**Comment by krzemin** [comment] 2015-12-01 22:21
It's very strange. I don't have any problems that you are describing when format conversion is enabled.

1. Did you installed pre-built package or used version compiled from source?
2. Which Qt version your qnapi binary is linked against?

**Comment by miniworm** [comment] 2015-12-05 10:42
I compile package myself since i'm on Ubuntu 14.04 and official package is only for 15.10. But i use the same script form Ubuntu official package so compilation is exactly the same. I've compiled official 0.2 and master from git. Here are dependencies:

Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libqt5core5a (>= 5.0.2), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 4.5), p7zip-full
Suggests: ffmpeg
Replaces: qnapi-gnome, qnapi-kde

**Comment by krzemin** [comment] 2015-12-06 11:11
So, what is the current Qt version? You can check it on about dialog, on the newest master.

**Comment by miniworm** [comment] 2015-12-06 12:22
![zrzut ekranu z 2015-12-06 13 16 38](https://cloud.githubusercontent.com/assets/1372625/11613294/1579dfce-9c1c-11e5-9335-bb1d0ebabd91.png)
Here is my about dialog - no Qt info ;-(

Anyway i've Qt available in Ubuntu 14.04 which is 5.2.1 - http://packages.ubuntu.com/trusty/libqt5core5a. Ubuntu 15.10 has 5.4.2.

**Comment by krzemin** [comment] 2015-12-06 13:59
Qt version in about dialog is available since that commit https://github.com/QNapi/qnapi/commit/605d3fd8abe12846598581643813e31bf4bd225e. You have to pull changes from the master and recompile it to see that.

But anyway - it's Qt 5.2.1, which is a bit old and it can be the root of the problems. Do you have possibillity to check one of these?

 * try to compile Qnapi not against pre-packaged Qt in your distribution, but download 5.5.x online installer for Linux here: https://www.qt.io/download-open-source/#section-2 and use qmake from the installation directory of 5.5.x and check whether the problems still persist
 * try to install/upgrade/set up virtual one ubuntu 15.10 and install qnapi from packages - so far no ubuntu 15.10 users reported such errors and I'm curious if you can reproduce them

**Comment by miniworm** [comment] 2015-12-09 20:03
I've tried qnapi from packages on Ubuntu 15.0 - version available is 0.1.9 - and can say that file type conversion works (at least for SRT). But regardless of selecting charset conversion or not in resulting file charset is some giberish (enca reports UTF-8 but it's not, it's something strange). Sadly i cannot chceck 02 version since it's not available in Ubuntu right now.

I'll try to compile Qnapi against Qt 5.5.1 but later in virtual machine - i don't want to mess-up things in my normal usage machine.

**Comment by krzemin** [comment] 2015-12-10 16:21
Yes, that was known problem in 0.1.9 (#34) and was fixed in 0.2.0. I expect that 0.2.0 (and newest master) compiled against Qt 5.5.x works fine.
Then we would need to bump up required Qt version for the project...

**Comment by miniworm** [comment] 2015-12-10 21:19
But it's not so good, at least for Ubuntu users since even in planned ubuntu 16.04 LTS right now Qt is at 5.4.2. So this requirement is very high. Solution: to provide for Linux not only tar.gz with source, but also DEB and RPM packages statically linked against Qt 5.5.

**Comment by krzemin** [comment] 2015-12-12 11:04
Ubuntu 15.10 has Qt 5.4.x and those strange problems with format conversion don't appear. Apparently their reasons were fixed before Qt 5.4.x (you can check it by compiling on Ubuntu 15.10). So actual "requirement" would be some Qt version between 5.2 and 5.3. I don't know and don't have time for investigating that. README clearly recommends the most recent version.

**Comment by miniworm** [comment] 2015-12-13 16:37
Ok, now i understand that in Ubuntu 14.04 the only solution is to have statically linked binary.

BTW - could you prepare 0.2.0 for Ubuntu? It's much better and this way it will be in 16.04 which is LTS so supported for next 5 years.

**Comment by miniworm** [comment] 2015-12-13 17:08
Nevermind for me but (README even in master) says that Qt 5.1+ (most recent 5.x recommended)

**Comment by krzemin** [comment] 2015-12-14 18:38
> Ok, now i understand that in Ubuntu 14.04 the only solution is to have statically linked binary.

Not necessarily. There are external repos with Qt 5.5.x. Look at https://github.com/QNapi/qnapi/blob/master/.travis.yml to see how the compilation environment on even older ubuntu distro is bootstraped (Travis by default uses 12.04 LTS).

> BTW - could you prepare 0.2.0 for Ubuntu?

The simple answer is: no. I'm not Debian/Ubuntu maintainer/packager. However I've submitted debian bugreport about new version available (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807758).

> Nevermind for me but (README even in master) says that Qt 5.1+ (most recent 5.x recommended)

Yes and that is true - 5.1 is minimal version required for compilation to succeed, but most recent one is recommended to have some features "unbugged".

**Closed** 2016-01-04 22:29 UTC
